# Generated by Django 3.0.2 on 2020-01-17 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banana', '0003_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='situation',
            field=models.TextField(default=''),
        ),
    ]
